version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: jumper
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    build: .
    container_name: prisma_migrate
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin@my_postgres:5432/jumper?schema=public"
    command: [ "sh", "-c", "npx prisma migrate dev --name init" ]
    volumes:
      - .:/app

volumes:
  postgres_data:
