version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: jumper-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: jumper
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migration:
    build: .
    container_name: jumper-database-migration
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://admin:admin@jumper-database:5432/jumper?schema=public"
    command: [ "sh", "-c", "npx prisma migrate dev --name init" ]
    volumes:
      - .:/app

  app:
    build: .
    container_name: jumper-backend
    depends_on:
      - postgres
      - migration
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "development"
      PORT: "8080"
      HOST: "localhost"
      CORS_ORIGIN: "http://localhost:3000"
      COMMON_RATE_LIMIT_WINDOW_MS: "1000"
      COMMON_RATE_LIMIT_MAX_REQUESTS: "1000"
      ALCHEMY_API_KEY: "2Oa20wsRdlq9TNp_6ebiXo41qn-nqi_W"
      JWT_SECRET: "f557fe81baf611aacaa6ec82a0a47918a6602d5353f73450f4ca862f7cf369aa"
    command: [ "sh", "-c", "npm run ci ; npx prisma generate ; npm run dev" ]

volumes:
  postgres_data:
